#ifndef CALCOLATRICE_CON_GIT_LIBRERIA_CALCOLATRICE_H
#define CALCOLATRICE_CON_GIT_LIBRERIA_CALCOLATRICE_H

#include <stdio.h>
typedef enum{ESCI, ADDIZIONE, SOTTRAZIONE, MOLTIPLICAZIONE, DIVISIONE}Operazione;
#endif //CALCOLATRICE_CON_GIT_LIBRERIA_CALCOLATRICE_H
